vcs: fixes
Plyushchenko/Java pull request #7
Opened 2017-04-02 14:00 UTC by Plyushchenko

2017-04-15 13:23 UTC, jzuken commented
а зачем было новый бранч делать?

2017-04-15 13:25 UTC, jzuken commented
фиксить конфиг тревиса удобно через git commit -amend, тогда тысячи новых коммитов не создаётся

2017-04-15 13:57 UTC, jzuken requested changes

2017-04-15 13:57 UTC, jzuken commented on src/main/java/VCS/Repo.java
> +     * Execute 'git init'
ну не "git" наверное всё же

2017-04-15 13:57 UTC, jzuken commented on src/main/java/VCS/Repo.java
> +     * @throws IOException Unknown IO problem
прямо так и неизвестная? а клиенту с ней что делать тогда?

2017-04-15 13:57 UTC, jzuken commented on src/main/java/VCS/RepoImpl.java
> +        } else {
и зачем тут тогда else, если return стоит выше?

2017-04-15 13:57 UTC, jzuken commented on src/main/java/VCS/Commands/BranchCommands/BranchCreateCommand.java
> +    public BranchCreateCommand(@NotNull FileSystem fileSystem, @NotNull String branchName) {
с точки зрения ООП всё стало гораздо лучше,  да

2017-04-15 13:57 UTC, jzuken commented on src/main/java/VCS/Objects/Branch.java
> +        return fileSystem.exists(fileSystem.buildRefLocation(branchName));
а чего бы ей в конструкторе это не проверять и не кидать исключение? или у вас реально может где-то создасться бранч с некорректным именем?

2017-04-15 13:57 UTC, jzuken commented on src/main/java/VCS/Commands/CheckoutCommands/CheckoutByBranchCommand.java
> +        //TODO: наверное, что-то удалять надо, а не только восстанваливать
ну надо рабочую копию/stage почистить, если она у вас есть

2017-04-15 13:57 UTC, jzuken commented on src/main/java/VCS/Data/FileSystemImpl.java
> +public class FileSystemImpl extends FileSystem {
ну тут можно было бы и статические методы оставить. всё-таки они даже в джаве такие везде

2017-04-15 13:57 UTC, jzuken commented on src/test/java/VCSTests.java
>  public class VCSTests {
про модульные тесты не забудьте ещё

2017-04-15 16:28 UTC, Plyushchenko commented
@jzuken 
Вроде как, код с головы до ног переписан - вот и новый бранч

2017-04-15 16:29 UTC, Plyushchenko commented on src/main/java/VCS/Objects/Branch.java
> +        return fileSystem.exists(fileSystem.buildRefLocation(branchName));
git checkout -b existingBranch
Что-то подобное я считаю плохой командой.

2017-04-16 07:07 UTC, jzuken commented
ну нет, ради этого новый бранч заводить не стоит однозначно. задача то не поменялась, и всю историю работы над ней хорошо бы иметь в одном месте. всё равно на вкладке files changed показывается только финальный дифф с базовой версией

2017-04-17 20:22 UTC, Plyushchenko commented on src/main/java/VCS/Repo.java
> +     * @throws IOException Unknown IO problem
@jzuken 
Я не знаю.
Я не могу нормально воспроизвести такое исключение. Могу написать клиенту "упс, пересоздай репозиториий"

2017-04-18 10:39 UTC, jzuken commented on src/main/java/VCS/Repo.java
> +     * @throws IOException Unknown IO problem
ну это гораздо лучше, чем показать стек вызовов. стек должен по-хорошему тоже писаться, но в ваш лог, а клиенту -- красивый понятный текст.

2017-04-24 18:27 UTC, Plyushchenko commented
@jzuken 
--amend нормально работает, когда ещё не запушил.
Если уже запушил, то

2017-05-27 16:51 UTC, closed without merging