ftp
Plyushchenko/Java pull request #9
Opened 2017-05-03 21:22 UTC by Plyushchenko

2017-05-19 08:43 UTC, jzuken requested changes

2017-05-19 08:43 UTC, jzuken commented on src/main/java/FTP/Client/ClientImpl.java
> +                throw new Exception();
зачем же так жёстко?

2017-05-19 08:43 UTC, jzuken commented on src/main/java/FTP/Client/Parser.java
> +                args[0] = "1";
это какой-то изврат, зачем заменять входные аргументы?
ну и константы для команд тоже хорошо бы унифицировать каким-нибудь енумом

2017-05-19 08:43 UTC, jzuken commented on src/main/java/FTP/Client/Commands/ListCommand.java
> +                response += is.readUTF();
ну они же неизменяемые, в цикле надо StringBuilder использовать

2017-05-19 08:43 UTC, jzuken commented on src/main/java/FTP/Data/ChannelByteReader.java
> +//TODO документация
угу

2017-05-19 08:43 UTC, jzuken commented on src/main/java/FTP/Data/ChannelByteWriter.java
> +        while (write(byteChannel) != -1);
лучше явно писать пустые скобки в таких местах, читиемость важнее

2017-05-19 08:43 UTC, jzuken commented on src/main/java/FTP/Client/UI/Main.java
> +                FTP.Client.Client client = new FTP.Client.ClientImpl();
не многовато клиентов? :)

2017-05-19 08:44 UTC, jzuken commented
при старте gui мне показали 
![image](https://cloud.githubusercontent.com/assets/705678/26240084/74e93d02-3c88-11e7-82cf-4a56b03fa660.png)
ну и дальше везде это же окошко при всех операциях. что я сделал не так как пользователь, нет возможности узнать

2017-05-19 08:45 UTC, jzuken commented
gui к серверу, кстати, совершенно необязательно было делать

2017-05-21 13:13 UTC, Plyushchenko commented on src/main/java/FTP/Client/Parser.java
> +                args[0] = "1";
@jzuken Протокол взаимодействия в условии такой.

2017-05-21 19:00 UTC, jzuken commented on src/main/java/FTP/Client/Parser.java
> +                args[0] = "1";
протокол заставляет вас подменять входные аргументы? :)

2017-05-28 15:48 UTC, jzuken commented
зачтено. за консольный вариант 10, за gui -- 9 из-за ошибки с no such folder

2017-05-28 16:14 UTC, closed without merging